// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyTracker.Infrastructure.Persistence;

namespace MoneyTracker.Infrastructure.Migrations
{
    [DbContext(typeof(MoneyTrackerDbContext))]
    partial class MoneyTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MoneyTracker.Infrastructure.Persistence.Entities.CurrencyEntity", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Code");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("MoneyTracker.Infrastructure.Persistence.Entities.PurchaseEntity", b =>
                {
                    b.Property<Guid>("PurchaseId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<string>("CurrencyCode")
                        .IsRequired();

                    b.Property<DateTime>("SpentAt");

                    b.HasKey("PurchaseId");

                    b.HasIndex("CurrencyCode");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("MoneyTracker.Infrastructure.Persistence.Entities.SalaryEntity", b =>
                {
                    b.Property<Guid>("SalaryId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<string>("CurrencyCode")
                        .IsRequired();

                    b.Property<DateTime>("ReceivedAt");

                    b.HasKey("SalaryId");

                    b.HasIndex("CurrencyCode");

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("MoneyTracker.Infrastructure.Persistence.Entities.PurchaseEntity", b =>
                {
                    b.HasOne("MoneyTracker.Infrastructure.Persistence.Entities.CurrencyEntity", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MoneyTracker.Infrastructure.Persistence.Entities.SalaryEntity", b =>
                {
                    b.HasOne("MoneyTracker.Infrastructure.Persistence.Entities.CurrencyEntity", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
